### ISSUE TITLE
Laravel Dependencies

### ISSUE THREAD

**Issue by trampish** [ScubaClick/scubaclick-keenio#1]
Hi ScubaClick, could you possibly update your composer.json file's Laravel dependencies to support 4.2.* ?

Thanks!

**Comment by shabushabu** [comment]
@silentFred Go for it. Happy Forking!

**Comment by ttaranto** [comment]
It works with Laravel 5? Thx

**Comment by shabushabu** [comment]
Nope, see the comments above.
